# -*- coding: utf-8 -*-
"""NeuroLearnAI_RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaN-TT_SVKzlGxlRTsh8vWtm-kXYX67d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import (
    train_test_split, cross_val_score,
    GridSearchCV, StratifiedKFold
)
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, ConfusionMatrixDisplay,
    roc_auc_score
)
import joblib
import warnings
warnings.filterwarnings('ignore')

# Plot style
plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'axes.spines.top': False,
    'axes.spines.right': False
})
PALETTE = ['#4C72B0','#DD8452','#55A868','#C44E52','#8172B2']

print('All libraries imported successfully!')
print(' Ready to build the model.')

from google.colab import files
uploaded = files.upload()

fname = list(uploaded.keys())[0]
print(f' Loaded file: {fname}')

if fname.endswith('.xlsx'):
    df = pd.read_excel(fname, sheet_name='Dataset')
else:
    df = pd.read_csv(fname)

print(f'\n Dataset loaded!')
print(f'   Rows     : {df.shape[0]:,}')
print(f'   Columns  : {df.shape[1]}')
print(f'   Original : {df["Student_ID"].str.startswith("NL").sum():,} students')
print(f'   Synthetic: {df["Student_ID"].str.startswith("SYN").sum():,} students')
df.head()

# Basic info
print('=== DATA TYPES ===')
print(df.dtypes)
print()
print('=== MISSING VALUES ===')
missing = df.isnull().sum()
print(missing[missing > 0] if missing.any() else 'None — dataset is clean ✅')
print()
print('=== NUMERIC SUMMARY ===')
df.describe().round(2)

# Target class distribution
counts = df['Preferred_Learning_Modality'].value_counts()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Learner Type Distribution', fontsize=15, fontweight='bold', y=1.01)

bars = axes[0].bar(counts.index, counts.values, color=PALETTE, edgecolor='white', linewidth=1.5)
axes[0].set_title('Count per Class', fontweight='bold')
axes[0].set_xlabel('Learning Modality')
axes[0].set_ylabel('Number of Students')
for bar in bars:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 15,
                 f'{int(bar.get_height()):,}', ha='center', fontweight='bold', fontsize=10)

axes[1].pie(counts.values, labels=counts.index, autopct='%1.1f%%',
            colors=PALETTE, startangle=140, wedgeprops={'edgecolor':'white','linewidth':2})
axes[1].set_title('Percentage Share', fontweight='bold')

plt.tight_layout()
plt.show()

# Average scores per learner type — key insight chart
score_cols = ['Text_Score','Audio_Score','Video_Score','Interactive_Score']
score_means = df.groupby('Preferred_Learning_Modality')[score_cols].mean().round(1)

ax = score_means.plot(kind='bar', figsize=(13, 6), color=PALETTE[:4],
                      edgecolor='white', linewidth=1)
ax.set_title('Average Scores per Learner Type\n(Each type dominates its own score)',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Learner Type')
ax.set_ylabel('Average Score')
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)
ax.legend(title='Score Type', bbox_to_anchor=(1.01, 1), loc='upper left')
ax.axhline(y=75, color='gray', linestyle='--', alpha=0.5, label='75 baseline')
plt.tight_layout()
plt.show()
print(score_means)

# Time taken per modality
time_cols = ['Text_Time_Taken_Minutes','Audio_Time_Taken_Minutes',
             'Video_Time_Taken_Minutes','Interactive_Time_Taken_Minutes']
time_means = df.groupby('Preferred_Learning_Modality')[time_cols].mean().round(2)

ax = time_means.plot(kind='bar', figsize=(13, 5), color=PALETTE[:4],
                     edgecolor='white', linewidth=1)
ax.set_title('Average Time Taken per Learner Type\n(Dominant modality → least time = most comfortable)',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Learner Type')
ax.set_ylabel('Minutes')
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)
ax.legend(title='Time Column', bbox_to_anchor=(1.01, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Categorical breakdowns
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Categorical Feature Breakdown by Learner Type', fontsize=13, fontweight='bold')

for ax, col in zip(axes, ['Engagement_Level','Learning_Speed','Gender']):
    ct = pd.crosstab(df['Preferred_Learning_Modality'], df[col], normalize='index') * 100
    ct.plot(kind='bar', ax=ax, edgecolor='white', linewidth=1)
    ax.set_title(col, fontweight='bold')
    ax.set_xlabel('')
    ax.set_ylabel('% of Learner Type')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha='right')
    ax.legend(fontsize=8)

plt.tight_layout()
plt.show()

# Correlation heatmap
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
corr = df[numeric_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))

plt.figure(figsize=(12, 8))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            linewidths=0.5, cbar_kws={'shrink': 0.8}, annot_kws={'size': 8})
plt.title('Feature Correlation Heatmap', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Drop irrelevant columns
df_clean = df.drop(columns=['Student_ID', 'Unnamed: 4', 'Adaptive_Recommendation'], errors='ignore').copy()

# Encode categorical features
CATEGORICAL_COLS = ['Gender', 'Education_Level', 'Engagement_Level', 'Learning_Speed']
label_encoders = {}

print('=== Label Encoding ===')
for col in CATEGORICAL_COLS:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    label_encoders[col] = le
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(f'  {col}: {mapping}')

# Encode target
TARGET = 'Preferred_Learning_Modality'
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(df_clean[TARGET])
X = df_clean.drop(columns=[TARGET])

print(f'\n=== Target Classes ===')
for i, cls in enumerate(target_encoder.classes_):
    print(f'  {i} → {cls}')

print(f'\n Preprocessing complete!')
print(f'   Features : {X.shape[1]}')
print(f'   Samples  : {X.shape[0]:,}')
X.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print('=== Train / Test Split (80 / 20) ===')
print(f'  Training samples : {X_train.shape[0]:,}')
print(f'  Testing  samples : {X_test.shape[0]:,}')
print(f'  Features         : {X_train.shape[1]}')
print()

# Verify stratification
train_dist = pd.Series(y_train).map(dict(enumerate(target_encoder.classes_))).value_counts(normalize=True)*100
test_dist  = pd.Series(y_test ).map(dict(enumerate(target_encoder.classes_))).value_counts(normalize=True)*100
dist_df = pd.DataFrame({'Train %': train_dist.round(1), 'Test %': test_dist.round(1)})
print('Class distribution in splits:')
print(dist_df)

print('Training Random Forest')

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print(' Random Forest trained!')
print(f'   Trees           : {rf_model.n_estimators}')
print(f'   Features used   : {rf_model.n_features_in_}')
print(f'   Classes         : {list(target_encoder.classes_)}')

y_pred      = rf_model.predict(X_test)
y_pred_prob = rf_model.predict_proba(X_test)

test_acc = accuracy_score(y_test, y_pred)
train_acc = accuracy_score(y_train, rf_model.predict(X_train))

# 5-fold cross validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf_model, X, y, cv=cv, scoring='accuracy')

print('=========================================')
print('        MODEL PERFORMANCE REPORT      ')
print(' ========================================')
print(f' Train Accuracy   : {train_acc:.4f} ({train_acc*100:.2f}%)  ')
print(f' Test  Accuracy   : {test_acc:.4f} ({test_acc*100:.2f}%)  ')
print(f' 5-Fold CV        : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}   ')
print(f' Baseline (old)   : 0.6000 (60.00%)  ')
print(f' Improvement      : +{(test_acc-0.60)*100:.1f}%               ')
print(' =========================================')


print
print('5-Fold Scores:', [f'{s:.4f}' for s in cv_scores])

# Detailed classification report
print('=== Classification Report ===')
print(classification_report(y_test, y_pred, target_names=target_encoder.classes_))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Confusion Matrix — Random Forest', fontsize=14, fontweight='bold')

# Raw counts
ConfusionMatrixDisplay(cm, display_labels=target_encoder.classes_).plot(
    cmap='Blues', colorbar=False, ax=axes[0])
axes[0].set_title('Raw Counts', fontweight='bold')
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=30, ha='right')

# Normalized
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ConfusionMatrixDisplay(cm_norm.round(2), display_labels=target_encoder.classes_).plot(
    cmap='Greens', colorbar=False, ax=axes[1])
axes[1].set_title('Normalized (Row %)', fontweight='bold')
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=30, ha='right')

plt.tight_layout()
plt.show()

# Cross-validation scores bar chart
fig, ax = plt.subplots(figsize=(8, 4))
bars = ax.bar([f'Fold {i+1}' for i in range(5)], cv_scores, color=PALETTE, edgecolor='white')
ax.axhline(cv_scores.mean(), color='red', linestyle='--', label=f'Mean = {cv_scores.mean():.4f}')
ax.set_ylim(0.8, 1.0)
ax.set_title('5-Fold Cross Validation Accuracy', fontweight='bold')
ax.set_ylabel('Accuracy')
ax.legend()
for bar in bars:
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.002,
            f'{bar.get_height():.4f}', ha='center', fontsize=9)
plt.tight_layout()
plt.show()

importances = rf_model.feature_importances_
feat_df = pd.DataFrame({'Feature': X.columns, 'Importance': importances})\
            .sort_values('Importance', ascending=False).reset_index(drop=True)

print('=== Top 10 Most Important Features ===')
print(feat_df.head(10).to_string(index=False))

# Plot
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Feature Importance Analysis', fontsize=14, fontweight='bold')

# Horizontal bar — all features
sorted_df = feat_df.sort_values('Importance', ascending=True)
colors_fi = plt.cm.RdYlGn(np.linspace(0.2, 0.9, len(sorted_df)))
axes[0].barh(sorted_df['Feature'], sorted_df['Importance'], color=colors_fi)
axes[0].set_title('All Features', fontweight='bold')
axes[0].set_xlabel('Importance Score')

# Top 8 pie
top8 = feat_df.head(8)
axes[1].pie(top8['Importance'], labels=top8['Feature'], autopct='%1.1f%%',
            colors=plt.cm.tab10.colors[:8], startangle=140,
            wedgeprops={'edgecolor':'white','linewidth':1.5})
axes[1].set_title('Top 8 Features Share', fontweight='bold')

plt.tight_layout()
plt.show()

param_grid = {
    'n_estimators'    : [200, 300],
    'max_depth'       : [None, 20, 30],
    'min_samples_split': [2, 5],
    'min_samples_leaf' : [1, 2],
}

grid_rf = GridSearchCV(
    RandomForestClassifier(class_weight='balanced', random_state=42, n_jobs=-1),
    param_grid,
    cv=3,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

print('\n=== Best Parameters ===')
print(grid_rf.best_params_)
print(f'\nBest CV Score  : {grid_rf.best_score_:.4f}')
print(f'Test  Accuracy : {accuracy_score(y_test, grid_rf.predict(X_test)):.4f}')

# Retrain with best params
best_model = grid_rf.best_estimator_
best_pred  = best_model.predict(X_test)
best_acc   = accuracy_score(y_test, best_pred)

print(f' Best Model Test Accuracy : {best_acc:.4f} ({best_acc*100:.2f}%)')
print()
print(classification_report(y_test, best_pred, target_names=target_encoder.classes_))

# Use best model going forward
rf_model = best_model

#Save Model
joblib.dump(rf_model,       'rf_model.pkl')
joblib.dump(label_encoders, 'label_encoders.pkl')
joblib.dump(target_encoder, 'target_encoder.pkl')
joblib.dump(list(X.columns),'feature_columns.pkl')

print('Model saved!')
print('  rf_model.pkl       — trained Random Forest')
print('  label_encoders.pkl — encoders for categorical features')
print('  target_encoder.pkl — encoder for learner type labels')
print('  feature_columns.pkl — feature column order')

# Download all saved files
from google.colab import files
for f in ['rf_model.pkl','label_encoders.pkl','target_encoder.pkl','feature_columns.pkl']:
    files.download(f)
print('\n All model files downloaded!')

# Predict Student type
new_student = {
    'Age'                           : 17,
    'Gender'                        : 'Male',
    'Education_Level'               : 'Grade 10',
    'Text_Score'                    : 78.0,
    'Audio_Score'                   : 61.0,
    'Video_Score'                   : 58.0,
    'Interactive_Score'             : 63.0,
    'Text_Time_Taken_Minutes'       : 4.2,
    'Audio_Time_Taken_Minutes'      : 6.1,
    'Video_Time_Taken_Minutes'      : 6.5,
    'Interactive_Time_Taken_Minutes': 5.8,
    'Attention_Score'               : 0.72,
    'Confidence_Level'              : 70.0,
    'Engagement_Level'              : 'High',
    'Repeated_Mistakes'             : 2,
    'Learning_Speed'                : 'Medium'
}

# Encode and predict
new_df = pd.DataFrame([new_student])
for col in CATEGORICAL_COLS:
    new_df[col] = label_encoders[col].transform(new_df[col].astype(str))

feature_cols = joblib.load('feature_columns.pkl')
pred_encoded = rf_model.predict(new_df[feature_cols])[0]
pred_label   = target_encoder.inverse_transform([pred_encoded])[0]
proba        = rf_model.predict_proba(new_df[feature_cols])[0]

print('===================================================')
print(f'    Predicted Learner Type : {pred_label:<15}')
print('===================================================')
print()
print('Confidence per class:')
for cls, prob in sorted(zip(target_encoder.classes_, proba), key=lambda x: -x[1]):
    bar  = '█' * int(prob * 40)
    star = ' ← predicted' if cls == pred_label else ''
    print(f'  {cls:<15} {prob:>6.2%}  {bar}{star}')

# Predict Student type
new_student = {
    'Age'                           : 19,
    'Gender'                        : 'Male',
    'Education_Level'               : 'Engineering Year 2',
    'Text_Score'                    : 53.3,
    'Audio_Score'                   : 76.2,
    'Video_Score'                   : 74.1,
    'Interactive_Score'             : 93.4,
    'Text_Time_Taken_Minutes'       : 4.8,
    'Audio_Time_Taken_Minutes'      : 7.7,
    'Video_Time_Taken_Minutes'      : 5.8,
    'Interactive_Time_Taken_Minutes': 3.0,
    'Attention_Score'               : 0.721,
    'Confidence_Level'              : 100.0,
    'Engagement_Level'              : 'High',
    'Repeated_Mistakes'             : 1,
    'Learning_Speed'                : 'Fast'
}

# Encode and predict
new_df = pd.DataFrame([new_student])
for col in CATEGORICAL_COLS:
    new_df[col] = label_encoders[col].transform(new_df[col].astype(str))

feature_cols = joblib.load('feature_columns.pkl')
pred_encoded = rf_model.predict(new_df[feature_cols])[0]
pred_label   = target_encoder.inverse_transform([pred_encoded])[0]
proba        = rf_model.predict_proba(new_df[feature_cols])[0]

print('===================================================')
print(f'    Predicted Learner Type : {pred_label:<15}')
print('===================================================')
print()
print('Confidence per class:')
for cls, prob in sorted(zip(target_encoder.classes_, proba), key=lambda x: -x[1]):
    bar  = '█' * int(prob * 40)
    star = ' ← predicted' if cls == pred_label else ''
    print(f'  {cls:<15} {prob:>6.2%}  {bar}{star}')

# Predict Student type
new_student = {
    'Age'                           : 20,
    'Gender'                        : 'Female',
    'Education_Level'               : 'Engineering Year 3',
    'Text_Score'                    : 76.8,
    'Audio_Score'                   : 56.3,
    'Video_Score'                   : 51.5,
    'Interactive_Score'             : 63.4,
    'Text_Time_Taken_Minutes'       : 3.1,
    'Audio_Time_Taken_Minutes'      : 4.9,
    'Video_Time_Taken_Minutes'      : 6.1,
    'Interactive_Time_Taken_Minutes': 3.9,
    'Attention_Score'               : 0.518,
    'Confidence_Level'              : 36.8,
    'Engagement_Level'              : 'High',
    'Repeated_Mistakes'             : 4,
    'Learning_Speed'                : 'Medium'
}

# Encode and predict
new_df = pd.DataFrame([new_student])
for col in CATEGORICAL_COLS:
    new_df[col] = label_encoders[col].transform(new_df[col].astype(str))

feature_cols = joblib.load('feature_columns.pkl')
pred_encoded = rf_model.predict(new_df[feature_cols])[0]
pred_label   = target_encoder.inverse_transform([pred_encoded])[0]
proba        = rf_model.predict_proba(new_df[feature_cols])[0]

print('===================================================')
print(f'    Predicted Learner Type : {pred_label:<15}')
print('===================================================')
print()
print('Confidence per class:')
for cls, prob in sorted(zip(target_encoder.classes_, proba), key=lambda x: -x[1]):
    bar  = '█' * int(prob * 40)
    star = ' ← predicted' if cls == pred_label else ''
    print(f'  {cls:<15} {prob:>6.2%}  {bar}{star}')

# Visualize batch prediction results
results_df = pd.DataFrame({
    'Student': [f"S{i+1}" for i in range(len(labels))],
    'Predicted': labels,
    'Confidence': [p.max() for p in probas]
})

color_map = {'Text':'#4C72B0','Audio':'#DD8452','Video':'#55A868',
             'Interactive':'#C44E52','Blended':'#8172B2'}
bar_colors = [color_map[l] for l in results_df['Predicted']]

fig, axes = plt.subplots(1, 2, figsize=(15, 5))
fig.suptitle('Batch Prediction Results', fontsize=14, fontweight='bold')

# Confidence bars
bars = axes[0].bar(results_df['Student'], results_df['Confidence']*100,
                   color=bar_colors, edgecolor='white', linewidth=1.5)
axes[0].set_title('Prediction Confidence per Student', fontweight='bold')
axes[0].set_ylabel('Confidence (%)')
axes[0].set_ylim(0, 110)
axes[0].axhline(90, color='red', linestyle='--', alpha=0.5, label='90% line')
for bar, lbl in zip(bars, results_df['Predicted']):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,
                 lbl[:3], ha='center', fontsize=8, fontweight='bold')
legend_patches = [mpatches.Patch(color=v, label=k) for k,v in color_map.items()]
axes[0].legend(handles=legend_patches, fontsize=8, loc='lower right')

# Predicted class distribution
pred_counts = results_df['Predicted'].value_counts()
axes[1].pie(pred_counts.values, labels=pred_counts.index, autopct='%1.0f%%',
            colors=[color_map[k] for k in pred_counts.index],
            startangle=140, wedgeprops={'edgecolor':'white','linewidth':2})
axes[1].set_title('Predicted Type Distribution (Batch)', fontweight='bold')

plt.tight_layout()
plt.show()

# Save batch predictions
batch_out = orig_list.copy()
batch_out['Predicted_Learner_Type'] = labels
batch_out['Confidence_%'] = [f'{p.max()*100:.1f}%' for p in probas]
for cls in target_encoder.classes_:
    idx = list(target_encoder.classes_).index(cls)
    batch_out[f'Prob_{cls}'] = [f'{p[idx]*100:.1f}%' for p in probas]

batch_out.to_csv('batch_predictions.csv', index=False)
files.download('batch_predictions.csv')
print(' Batch predictions saved & downloaded!')